spring:
  profiles:
    active: local
  application:
    name: nugul-ticket

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    
client:
  id: ${CLIENT_ID}

cloud:
  aws:
    credentials:
      access-key: ${SQS_ACCESS_KEY}
      secret-key: ${SQS_SECRET_KEY}
    region:
      static: ${SQS_REGION}
    stack:
      auto: false

    sqs:
      queue:
        name: NugulPayments.fifo
        url: ${SQS_PAYMENTS_URL}

    sns:
      ticket:
        topic:
          arn: ${SNS_TICKET_TOPIC}
      payment:
        topic:
          arn: ${SNS_PAYMENT_TOPIC}

toss:
  key:
    secret-key: ${TOSS_SECRET_KEY}

grpc:
  server:
    port: 50052